# Generated by Django 4.2.7 on 2023-11-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='E-mail')),
                ('first_name', models.CharField(max_length=30, verbose_name='이름')),
                ('last_name', models.CharField(max_length=30, verbose_name='성')),
                ('mobile_number', models.CharField(max_length=30, verbose_name='휴대전화번호')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저',
                'db_table': 'users',
            },
        ),
    ]
