# Generated by Django 4.2.7 on 2023-11-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_knoweruser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='knoweruser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='어드민 '),
        ),
    ]
