databases:
  - name: knower
    databaseName: knower
    user: knower
    region: singapore

services:
  - type: web
    name: knower-api
    runtime: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: knower
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
